import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import React from 'react'
import TodoList from './page'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  const todoListUseCase = {
    getTodoItems: async () => [
      { id: 1, title: 'todo 1', isCompleted: true },
      { id: 2, title: 'todo 2', isCompleted: false },
      { id: 3, title: 'todo 3', isCompleted: false },
    ],
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TodoList todoListUseCase={todoListUseCase} />
      </body>
    </html>
  )
}
