import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import React from 'react'
import TodoList from './page'
import { LoadTodoList } from '@/usecases/types/LoadTodoList'
import { createLoadTodoList } from '@/usecases/createLoadTodoList'
import { TodoListRepository } from '@/repositories/TodoListRepository'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  const loadTodoList = createLoadTodoList(new TodoListRepository())

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TodoList loadTodoList={loadTodoList} />
      </body>
    </html>
  )
}
